### ISSUE TITLE
Run tests in all three configurations for other packages

### ISSUE THREAD

**Issue by alex-konovalov** [gap-infra/gap-docker-pkg-tests-master-devel#10]
The next step in improving this would be to run tests three times:
- with only needed packages loaded (maybe with disabled obsoletes, if possible)
- with default packages
- with all packages loaded.

**Comment by fingolfin** [comment]
@alex-konovalov isn't this all done? Or else I don't understand what exactly this issue is about?

**Comment by alex-konovalov** [comment]
Closed in https://github.com/gap-infra/gap-docker-pkg-tests-master-devel/commit/965b9beb4119cb97a9b927cb7a187746d297798c
