### ISSUE TITLE
New packages with tests

### ISSUE THREAD

**Issue by alex-konovalov** [gap-infra/gap-docker-pkg-tests-master-devel#16]
Add tests for:
- [x] https://github.com/ffloresbrito/aaa (see https://github.com/ffloresbrito/aaa/issues/1)
- [x] https://github.com/lbfm-rwth/CaratInterface
- [x] https://github.com/gap-packages/fwtree
- [x] https://github.com/gap-packages/liering
- [x] https://github.com/le-on/ModularGroup (see https://github.com/le-on/ModularGroup/issues/2)
- [x] https://github.com/gap-packages/PARIInterface (see https://github.com/gap-packages/PARIInterface/issues/4)
- [x] https://github.com/oysteins/QPA2/ (see https://github.com/oysteins/QPA2/issues/27)
- [x] https://github.com/gap-packages/quagroup
- [x] https://github.com/gap-packages/sla

For new tests for packages redistributed with GAP, see https://github.com/gap-packages/gap-packages.github.io/issues/9

**Comment by fingolfin** [comment]
@alex-konovalov can this be closed now?

**Comment by alex-konovalov** [comment]
Yes (more packages may have tests, and it's an ongoing work to add them, but no point in keeping an old issue)
