### ISSUE TITLE
Check that version loaded is version cloned

### ISSUE THREAD

**Issue by alex-konovalov** [gap-infra/gap-docker-pkg-tests-master-devel#9]
See https://github.com/gap-packages/gap-docker-pkg-tests-master-devel/issues/5 - it may happen that if the package is not loadable from the cloned repository, GAP will load the one from the GAP distribution. One should check the path to the package version that is loaded and trigger an error if the cloned version is not usable.

**Comment by fingolfin** [comment]
I would suggest to use `SetPackagePath` for this purpose, that's precisely what it was made for.
